### PR TITLE
Plugin constants added

### PR DESCRIPTION
**Pull request by hsleonis**
It is best practice to define plugin dir, path etc.
[Reference](https://www.doitwithwp.com/declare-constants-easily-reference-plugin-files)

### CODE REVIEW

**Comment by hsleonis** [comment]
Hi @ArthurGareginyan,
You have a cool project here. Hope my contribution helps.

Regards.

**Comment by ArthurGareginyan** [comment]
Hi @hsleonis,
Thanks! Your contribution is very helps. Now I now about the "use strict" directive in JS. Thank you!

Regards,
Arthur

**Comment by hsleonis** [comment]
Thanks @ArthurGareginyan ,
Hopefully this plugin will be a great success.

Best regards.

**Comment by ArthurGareginyan** [comment]
Thank you very much!

Regards,
Arthur

**Pull request merged**
